# Generated by Django 5.1.3 on 2024-12-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='patients', to='dashboard.doctor'),
        ),
    ]
